name: somkrobkid
favicon: null
layout_spectrum: 0.786879145540297
typography_spectrum: 0.5995713549200445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.04503555246628821
  lightness: 0.9763655962888151
  saturation: 0.11440836731344461
  rhythmicContrast: 0.6146593294106424
purpose: []
