name: somkrobkid
favicon: null
layout_spectrum: 0.24163
typography_spectrum: 0.60577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3268a6'
    - '#5285ba'
    - '#7fb4d6'
    - '#beccd9'
  brandStrength: 0
  lightness: 0.9763655962888151
  saturation: 0.11440836731344461
  rhythmicContrast: 0.6146593294106424
purpose: []
